from tkinter import *
def Girasol():

	def Siembra():
		
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#ffd86f")
		Titulo=Label(miFrame, text="Siembra de un Girasol", font=("Arial", 15), bg="#ffd86f")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" Normalmente, las semillas de girasol se plantan en primavera para recoger sus frutos en verano.", bg="#ffd86f")
		actividad.grid(row=1,column=0, sticky="w")
		actividad2=Label(miFrame, text="La profundidad de siembra depende de la temperatura, humedad y tipo de suelo", bg="#ffd86f")
		actividad2.grid(row=2,column=0, sticky="w")
		actividad3=Label(miFrame, text="La profundidad de siembra depende de la temperatura, humedad y tipo de suelo:", bg="#ffd86f")
		actividad3.grid(row=2,column=0, sticky="w")
		actividad4=Label(miFrame, text="En primaveras cálidas con suelos pesados y húmedos, la profundidad de siembra es de 5 a 6 cm.", bg="#ffd86f")
		actividad4.grid(row=3,column=0, sticky="w", padx=15)
		actividad4=Label(miFrame, text="En primaveras secas con suelos ligeros y poco húmedos, la profundidad de siembra es de 7 a 9 cm.", bg="#ffd86f")
		actividad4.grid(row=4,column=0, sticky="w", padx=15)

		rootSiembra.mainloop()

	def Regado():
		rootRegado=Toplevel()
		miFrame=Frame(rootRegado)
		miFrame.pack()
		rootRegado.title("Riego")
		miFrame.config(bg="#ffd86f")
		Titulo=Label(miFrame, text="Regado", font=("Arial", 15), bg="#ffd86f")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="El girasol aprovecha el agua de forma mucho más eficiente en condiciones de escasez, aunque esto provoca que sus flores y frutos no prosperen correctamente.", wraplength=400, bg="#ffd86f")
		actividad.grid(row=1,column=0, sticky="w")
		actividad2=Label(miFrame, text="Si los regamos de forma adecuada, aun considerando que es un cultivo relativamente de secano, potenciaremos el crecimiento de la planta y su óptimo desarrollo.", wraplength=400, bg="#ffd86f")
		actividad2.grid(row=2,column=0, sticky="w")
		rootRegado.mainloop()

	def Clima():
		rootClima=Toplevel()
		miFrame=Frame(rootClima)
		miFrame.pack()
		miFrame.config(bg="#ffd86f")
		rootClima.title("Clima")
		Titulo=Label(miFrame, text="Clima", font=("Arial", 15), bg="#ffd86f")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="El cultivo del girasol se habitúa a diferentes condiciones climáticas.", bg="#ffd86f")
		actividad.grid(row=1,column=0, sticky="w")
		actividad=Label(miFrame, text="Para la floración y maduración de los frutos requiere temperaturas elevadas, la ideal se encuentra entre 20 y 25ºC. ", wraplength=400, bg="#ffd86f")
		actividad.grid(row=2,column=0, sticky="w")

		rootClima.mainloop()


	global imagenfondo
	global labelfondo
	rootG=Toplevel()
	miFrame=Frame(rootG)
	miFrame.pack()
	rootG.title("Girasol")
	rootG.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondog.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=Siembra, bg="#ffd86f")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=Regado, bg="#ffd86f")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=Clima, bg="#ffd86f")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootG.mainloop()


def Rosa():
	def SiembraRosa():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="Pink")
		Titulo=Label(miFrame, text="Siembra de una Rosa", font=("Arial", 15),bg="Pink")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Elegir una ubicación con al menos seis horas diarias de sol",bg="Pink")
		actividad.grid(row=1,column=0, sticky="w")
		actividad2=Label(miFrame, text="Dejar espacio entre rosal y rosal para que puedan oxigenarse, o hacerlo en un emplazamiento a cubierto del viento nos facilitarán enormemente su correcto cultivo.", wraplength=300,bg="Pink")
		actividad2.grid(row=2,column=0, sticky="w")
		rootSiembra.mainloop()
	def RegadoRosa():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Regado")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="Pink")
		Titulo=Label(miFrame, text="Regado de una Rosa", font=("Arial", 15),bg="Pink")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Los Rosales tienen la ventaja de que arraigan profundamente y aguantan bastante sin riego. No obstante, debes procurar abundante agua para que las floraciones sean espectaculares. Las plantas en flor siempre consumen mucha agua. ",bg="Pink", wraplength=300)
		actividad.grid(row=1,column=0, sticky="w")
		actividad2=Label(miFrame, text="1. Durante el primer año desde la plantación, el riego no debe descuidarse, porque todavía las raíces no son profundas ", wraplength=300,bg="Pink")
		actividad2.grid(row=2,column=0, sticky="w")
		actividad3=Label(miFrame, text="2. En invierno, que no tiene hojas, es evidente que no necesitará ningún aporte de riego. Si está en maceta se debe regar algo para que no se resequen las raíces, pero muy poco.", wraplength=300,bg="Pink")
		actividad3.grid(row=3,column=0, sticky="w")
		rootSiembra.mainloop()
	def ClimaRosa():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()

		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="Pink")
		rootSiembra.title("Clima")
		Titulo=Label(miFrame, text="Clima donde crece una Rosa", font=("Arial", 15),bg="Pink")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="La rosa es un planta de día largo. Por tanto, en los meses de verano, cuando prevalecen elevadas intensidades luminosas y larga duración del día, la producción de flores es más alta que durante los meses de invierno. ", wraplength=300,bg="Pink")
		actividad.grid(row=1,column=0, sticky="w")
		actividad2=Label(miFrame, text="A pesar de tratarse de una planta de día largo, es necesario el sombreo durante el verano e incluso en primavera y en otoño, dependiendo de la climatología del lugar. ", wraplength=300,bg="Pink")
		actividad2.grid(row=2,column=0, sticky="w")
		rootSiembra.mainloop()



	rootR=Toplevel()
	miFrame=Frame(rootR)
	miFrame.pack()
	rootR.title("Rosa")
	rootR.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondorosa.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraRosa, bg="#ff8cbd")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2,command=RegadoRosa, bg="#ff8cbd")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaRosa, bg="#ff8cbd")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootR.mainloop()

def AloeVera():
	def SiembraAloe():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		rootSiembra.title("Siembra")
		miFrame.config(bg="#c8ffb4")
		Titulo=Label(miFrame, text="Siembra de un Aloe Vera", font=("Arial", 15), bg="#c8ffb4")
		Titulo.grid(row=0, column=0, columnspan=2)
		labelactividad=Label(miFrame, text="Epoca para Plantarlo:", font=("Arial", 12), bg="#c8ffb4")
		labelactividad.grid(row=1, column=0, sticky="w")
		labelactividad=Label(miFrame, text="La mejor época del año para plantar el aloe vera es en otoño o primavera.", bg="#c8ffb4")
		labelactividad.grid(row=2, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Donde plantarlo:", font=("Arial", 12), bg="#c8ffb4")
		labelactividad.grid(row=3, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Ubicarla en un lugar algo húmedo y donde reciba la luz del sol. Lo conveniente sería que estuviese expuesta a la luz solar entre 8 y 10 horas", wraplength=300, bg="#c8ffb4")
		labelactividad.grid(row=4, column=0, sticky="w")
		rootSiembra.mainloop()
	def RegadoAloe():
		rootRegado=Toplevel()
		miFrame=Frame(rootRegado)
		miFrame.pack()
		rootRegado.title("Regado")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#c8ffb4")
		Titulo=Label(miFrame, text="Regado de un Aloe Vera", font=("Arial", 15), bg="#c8ffb4")
		Titulo.grid(row=0, column=0, columnspan=2)
		labelactividad=Label(miFrame, text="Debes regar tu aloe vera cada 15 o 20 días, utilizando poca agua y vertiéndola directamente sobre la tierra, sin dejar la maceta encharcada.", wraplength=300, bg="#c8ffb4")
		labelactividad.grid(row=1, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Ten en cuenta que si te excedes en la cantidad de agua, la planta de aloe vera puede llegar a pudrirse.", wraplength=300, bg="#c8ffb4")
		labelactividad.grid(row=2, column=0, sticky="w")
		rootRegado.mainloop()
	def ClimaAloe():
		rootClima=Toplevel()
		miFrame=Frame(rootClima)
		miFrame.pack()
		rootClima.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#c8ffb4")
		Titulo=Label(miFrame, text="Clima donde crece un Aloe Vera", font=("Arial", 15), bg="#c8ffb4")
		Titulo.grid(row=0, column=0, columnspan=2)
		labelactividad=Label(miFrame, text="Prefiere clima seco, temperaturas entre 18 y 40°C, precipitación pluvial de 400 a 2.500 mm anuales y humedad relativa de 65 a 85%.", wraplength=300, bg="#c8ffb4")
		labelactividad.grid(row=1, column=0, sticky="w")
		labelactividad2=Label(miFrame, text="Crece en lugares soleados, terronosos, rocosos y pedregosos. Se desarrolla en cualquier tipo de tierra, pero es necesario que tenga buen drenaje. Prefiere suelos arenosos, franco arenosos y franco arenoso-arcillosos, con suficiente materia orgánica.", wraplength=300, bg="#c8ffb4")
		labelactividad2.grid(row=2, column=0, sticky="w")
		rootClima.mainloop()
	rootA=Toplevel()
	miFrame=Frame(rootA)
	miFrame.pack()
	rootA.title("Aloe Vera")
	rootA.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondoaloe.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraAloe, bg="#c8ffb4")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RegadoAloe, bg="#c8ffb4")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaAloe, bg="#c8ffb4")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootA.mainloop()

def Hortensia():
	def SiembraHort():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#c8a8fe")
		Titulo=Label(miFrame, text="Siembra de una Hortensia", font=("Arial", 15), bg="#c8a8fe")
		Titulo.grid(row=0, column=0, columnspan=2)
		labelactividad=Label(miFrame, text="Donde Sembrar", wraplength=300, font=("Arial", 11), bg="#c8a8fe")
		labelactividad.grid(row=1, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Necesitan una intensidad de luz moderada. No soportan bien luz directa durante las horas de sol más fuerte, especialmente en verano.", wraplength=300, bg="#c8a8fe")
		labelactividad.grid(row=2, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Como se Prepara la Tierra?", wraplength=300, font=("Arial", 11), bg="#c8a8fe")
		labelactividad.grid(row=3, column=0, sticky="w")
		labelactividad=Label(miFrame, text="Con un buen aporte de materia orgánica y humus de lombriz. Evita sembrar hortensias en un terreno muy seco. Humedece el terreno, sin encharcar.", bg="#c8a8fe", wraplength=300)
		labelactividad.grid(row=4, column=0, sticky="w")
		rootSiembra.mainloop()
	def RiegoHort():
		rootRiego=Toplevel()
		miFrame=Frame(rootRiego)
		miFrame.pack()
		rootRiego.title("Regado")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#c8a8fe")
		Titulo=Label(miFrame, text="Riego de una Hortensia", font=("Arial", 15), bg="#c8a8fe")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="¿Cómo regamos?", font=("Arial", 11), bg="#c8a8fe")
		actividad.grid(row=1, column=0,sticky="w")
		actividad=Label(miFrame, text="Ideal, riego por goteo", bg="#c8a8fe")
		actividad.grid(row=2, column=0,sticky="w")
		actividad=Label(miFrame, text="¿Cada cuánto regamos?", font=("Arial", 11), bg="#c8a8fe")
		actividad.grid(row=3, column=0,sticky="w")
		actividad=Label(miFrame, text=" Necesitan agua, especialmente en verano. Riégalas por la mañana o por la noche. Si las hojas se vuelven de color marrón es un indicador de falta de agua.", wraplength=300, bg="#c8a8fe")
		actividad.grid(row=4, column=0,sticky="w")
		rootRiego.mainloop()
	def ClimaHort():
		rootClima=Toplevel()
		miFrame=Frame(rootClima)
		miFrame.pack()
		rootClima.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#c8a8fe")
		Titulo=Label(miFrame, text="Clima donde crece una Hortensia", font=("Arial", 15), bg="#c8a8fe")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" Las hortensias les gusta el sol de la mañana o sol que viene del este, pero esto solo en zonas de clima suave si el clima es cálido tendrán que estar a sol indirecto.", wraplength=300, bg="#c8a8fe")
		actividad.grid(row=2, column=0,sticky="w")
		actividad2=Label(miFrame, text="  En zonas templadas pueden prosperan con algo de sombra.", wraplength=300, bg="#c8a8fe")
		actividad2.grid(row=3, column=0,sticky="w")
		rootClima.mainloop()
	rootH=Toplevel()
	miFrame=Frame(rootH)
	miFrame.pack()
	rootH.title("Hortensia")
	rootH.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondoh.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraHort, bg="#c8a8fe")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RiegoHort, bg="#c8a8fe")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaHort, bg="#c8a8fe")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootH.mainloop()


def Manzanilla():
	def SiembraMan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#ffe9a4")
		Titulo=Label(miFrame, text="Siembra de una Manzanilla", font=("Arial", 15), bg="#ffe9a4")
		Titulo.grid(row=0, column=0, columnspan=2)
		Titulo=Label(miFrame, text="Como plantar manzanilla", font=("Arial", 11), bg="#ffe9a4")
		Titulo.grid(row=1, column=0, sticky="w")
		actividad=Label(miFrame, text="Se debe sembrar a una profundidad máxima de 0,5 cm del suelo, o que este simplemente presione ligeramente las semillas en el suelo.", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=2, column=0, sticky="w")
		actividad=Label(miFrame, text="Las semillas de manzanilla suelen germinar pasada una a dos semanas", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=3, column=0, sticky="w")
		actividad=Label(miFrame, text="La separación entre plantas puede ser de 30 a 45 cm entre plantas.", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=4, column=0, sticky="w")
		rootSiembra.mainloop()
	def RiegoMan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Regado")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#ffe9a4")
		Titulo=Label(miFrame, text="Riego de una Manzanilla", font=("Arial", 15), bg="#ffe9a4")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="La manzanilla necesita tener un suelo bien húmedo por lo que se recomienda regar con frecuencia y agregar una capa de mantillo para conservar la humedad de la tierra.", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=1, column=0, sticky="w")
		actividad=Label(miFrame, text="Evita que la tierra se encharque. Por otra parte, no mojes las flores durante el riego para que no ennegrezcan.", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=2, column=0, sticky="w")
		rootSiembra.mainloop()
	def ClimaMan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#ffe9a4")
		Titulo=Label(miFrame, text="Clima para que crezca una Manzanilla", font=("Arial", 15), bg="#ffe9a4")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Si la temperatura es mayor a los 35°C puede dañar a nuestras plantas, por lo que debemos protegerla con malla sombra o mover nuestras macetas a un lugar protegido.", wraplength=300, bg="#ffe9a4")
		actividad.grid(row=1, column=0, sticky="nswe")
	rootM=Toplevel()
	miFrame=Frame(rootM)
	miFrame.pack()
	rootM.iconbitmap("girasol3.ico")
	rootM.title("Manzanilla")
	imagenfondo=PhotoImage(file="img/fondom.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraMan, bg="#ffe9a4")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RiegoMan, bg="#ffe9a4")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaMan, bg="#ffe9a4")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootM.mainloop()


def Tulipan():
	def SiembraTulipan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#ffc0e2")
		Titulo=Label(miFrame, text="Siembra de un Tulipan", font=("Arial", 15), bg="#ffc0e2")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Los tulipanes florecen en primavera y para que así sea, se deben plantar durante el otoño.", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=1, column=0, sticky="w")
		actividad=Label(miFrame, text=" Si se siembran antes de que la tierra se ponga fría y dura, se podrá lograr un buen crecimiento y una gran floración.", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=2, column=0, sticky="w")
		rootSiembra.mainloop()
	def RiegoTulipan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Riego")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#ffc0e2")
		Titulo=Label(miFrame, text="Riego de un Tulipan", font=("Arial", 15), bg="#ffc0e2")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" El riego es constante durante toda la temporada y debes regar la planta cuando el sustrato a 3 centímetros del profundidad empiece a secarse.", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=2, column=0, sticky="w")
		actividad=Label(miFrame, text="  Riega generosamente pero sin llegar a encharcar la maceta ya que los bulbos de tulipan se pudren en suelos demasiado mojados.", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=3, column=0, sticky="w")
		rootSiembra.mainloop()
	def ClimaTulipan():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#ffc0e2")
		Titulo=Label(miFrame, text="Clima para que crezca un Tulipan", font=("Arial", 15), bg="#ffc0e2")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" Los tulipanes no pueden crecer en un clima cálido, ya que necesitan frío en invierno para desarrollarse. ", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=3, column=0, sticky="w")
		actividad=Label(miFrame, text="Los bulbos de tulipán se deben plantar en octubre/noviembre y florecen de abril a junio. Se cultivan en casa o en los jardines ", wraplength=300, bg="#ffc0e2")
		actividad.grid(row=4, column=0, sticky="w")
		rootSiembra.mainloop()
	rootT=Toplevel()
	miFrame=Frame(rootT)
	miFrame.pack()
	rootT.iconbitmap("girasol3.ico")
	rootT.title("Tulipan")
	imagenfondo=PhotoImage(file="img/fondot.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraTulipan, bg="#ffc0e2")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RiegoTulipan, bg="#ffc0e2")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaTulipan, bg="#ffc0e2")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootT.mainloop()

def Diente():

	def SiembraDiente():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#d9cccc")
		Titulo=Label(miFrame, text="Siembra de un Diente de Leon", font=("Arial", 15), bg="#d9cccc")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Las semillas se pueden sembrar cada dos semanas en filas cortas para tener una cosecha constante de esta planta.", wraplength=300, bg="#d9cccc")
		actividad.grid(row=1, column=0, sticky="w")
		actividad=Label(miFrame, text="Sin embargo, en lo que se refiere a como plantar diente de león, es importante la planificación para no sembrar más semillas de lo que se va a usar, pues el crecimiento de las flores debe ser controlada manualmente. ", wraplength=300, bg="#d9cccc")
		actividad.grid(row=2, column=0, sticky="w")
		rootSiembra.mainloop()
	def RiegoDiente():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Regado")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#d9cccc")
		Titulo=Label(miFrame, text="Riego de un Diente de Leon", font=("Arial", 15), bg="#d9cccc")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="Los riegos de un diente de leon deben de ser moderados a escasos o nulos, si tenemos buenas lluvias. Gusta de un ambiente humedo, pero igual, puede soportar sequias", wraplength=300, bg="#d9cccc")
		actividad.grid(row=1, column=0, sticky="w")
		rootSiembra.mainloop()
	def ClimaDiente():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config( bg="#d9cccc")
		Titulo=Label(miFrame, text="Clima para que crezca tu Diente de Leon", font=("Arial", 15), bg="#d9cccc")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="La temperatura óptima del suelo para la germinación de las semillas es de 10 a 25 ° C. Estas pueden tardar en germinar de 14 a 21 días", wraplength=300, bg="#d9cccc")
		actividad.grid(row=1, column=0, sticky="nswe")
		actividad=Label(miFrame, text="Posteriormente, la floración se inicia pasado los 56 a 105 días de la siembra.", wraplength=300, bg="#d9cccc")
		actividad.grid(row=2, column=0, sticky="nswe")
		rootSiembra.mainloop()


	rootD=Toplevel()
	miFrame=Frame(rootD)
	miFrame.pack()
	rootD.title("Diente de Leon")
	rootD.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondod.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraDiente, bg="#d9cccc")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RiegoDiente, bg="#d9cccc")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaDiente, bg="#d9cccc")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootD.mainloop()
def Nopal():
	def SiembraNopal():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Siembra")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#a4ca68")
		Titulo=Label(miFrame, text="Siembra de un Nopal", font=("Arial", 15), bg="#a4ca68")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" Coloca una o dos semillas en la parte superior de la tierra. Presiónalas suavemente para que entren en la tierra y cúbrelas con 0,6 cm (1/4 de pulgada) de tierra", wraplength=300, bg="#a4ca68")
		actividad.grid(row=2, column=0, sticky="nswe")
		actividad=Label(miFrame, text=" Agrega un poco de agua. La tierra debe estar húmeda, pero no mojada.", wraplength=300, bg="#a4ca68")
		actividad.grid(row=3, column=0, sticky="nswe")
		rootSiembra.mainloop()
	def RiegoNopal():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Riego")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#a4ca68")
		Titulo=Label(miFrame, text="Riego de un Nopal", font=("Arial", 15), bg="#a4ca68")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text="El nopal necesita algo de riego, sobre todo en su edad juvenil, una vez a la semana en primavera-verano y una al mes en otoño-invierno serán suficientes, siempre que no llueva claro está.", wraplength=300, bg="#a4ca68")
		actividad.grid(row=2, column=0, sticky="nswe")
		rootSiembra.mainloop()
	def ClimaNopal():
		rootSiembra=Toplevel()
		miFrame=Frame(rootSiembra)
		miFrame.pack()
		rootSiembra.title("Clima")
		imagenfondo=PhotoImage(file="img/fondo.png")
		labelfondo=Label(miFrame, image=imagenfondo)
		miFrame.config(bg="#a4ca68")
		Titulo=Label(miFrame, text="Clima para cultivar un Nopal", font=("Arial", 15), bg="#a4ca68")
		Titulo.grid(row=0, column=0, columnspan=2)
		actividad=Label(miFrame, text=" El tiempo ideal para planear plantar nopales es a finales del invierno cuando la tierra empieza a calentarse y ha pasado la amenaza de las heladas.", wraplength=300, bg="#a4ca68")
		actividad.grid(row=2, column=0, sticky="nswe")
		rootSiembra.mainloop()

	rootN=Toplevel()
	miFrame=Frame(rootN)
	miFrame.pack()
	rootN.title("Nopal")
	rootN.iconbitmap("girasol3.ico")
	imagenfondo=PhotoImage(file="img/fondon.png")
	labelfondo=Label(miFrame, image=imagenfondo)
	labelfondo.place(relwidth=1, relheight=1)

	botonSiembra=Button(miFrame, text="Siembra", width=15, height=2, command=SiembraNopal, bg="#a4ca68")
	botonSiembra.grid(row=0, column=0, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Regado", width=15, height=2, command=RiegoNopal, bg="#a4ca68")
	botonRegado.grid(row=0, column=1, padx=5, pady=5)
	botonRegado=Button(miFrame, text="Clima", width=15, height=2, command=ClimaNopal, bg="#a4ca68")
	botonRegado.grid(row=1, column=0, padx=5, pady=5, columnspan=2)
	rootN.mainloop()






def ventana_inicio():
    global ventana_principal
    pestas_color="DarkGrey"
    ventana_principal=Tk()
    ventana_principal.geometry("300x250")#DIMENSIONES DE LA VENTANA
    ventana_principal.title("GreenWorld")#TITULO DE LA VENTANA
    ventana_principal.iconbitmap("girasol3.ico")
    miFrame=Frame(ventana_principal)
    imagenfondo=PhotoImage(file="img/fondoh.png")
    labelfondo=Label(miFrame, image=imagenfondo)
    labelfondo.place(relwidth=1, relheight=1)
    miFrame.pack()
    titulo=Label(miFrame, text="Bienvenido a GreenWorld", bg="LightGreen", width="35", height="2", font=("Calibri", 13))#ETIQUETA CON TEXTO
    titulo.grid(row=0, column=0)
    espacio=Label(miFrame,text="", bg="#c8a8fe")
    espacio.grid(row=1, column=0)

    acceder=Button(miFrame,text="Acceder", height="2", width="30", bg=pestas_color) #BOTÓN "Acceder"
    acceder.grid(row=2, column=0)
    espacio2=Label(miFrame,text="", bg="#c8a8fe")
    espacio2.grid(row=3, column=0)
    registrarse=Button(miFrame,text="Registrarse", height="2", width="30", bg=pestas_color) #BOTÓN "Registrarse".
    registrarse.grid(row=4, column=0)
    espacio3=Label(miFrame,text="", bg="#c8a8fe")
    espacio3.grid(row=5, column=0, columnspan=1)
    espacio3=Label(miFrame,text="", bg="#c8a8fe")
    espacio3.grid(row=6, column=0)
    espacio3=Label(miFrame,text="", bg="#c8a8fe")
    espacio3.grid(row=7, column=0)
    espacio3=Label(miFrame,text="", bg="#c8a8fe")
    espacio3.grid(row=8, column=0)
    ventana_principal.mainloop()
